
-- TODO: User table
CREATE TABLE USER (
  USER_ID       VARCHAR(100)        NOT NULL,
  PASSWORD      VARCHAR(100)        NOT NULL,
  FIRST_NAME    VARCHAR(100)        NOT NULL,
  LAST_NAME     VARCHAR(100)        NOT NULL,
  DATE_OF_BIRTH TIMESTAMP           NOT NULL,

  CONSTRAINT PK_TEST_DEV PRIMARY KEY (TEST_ID)
);

CREATE TABLE WASTE_BAG (
  BAG_ID            VARCHAR(100)      NOT NULL,
  WASTE_CATEGORY    VARCHAR(100)      NOT NULL,
  DATE_OF_DISPOSAL  VARCHAR(100)      NOT NULL,
  USER_ID VARCHAR(100) REFERENCES USER (USER_ID) ON DELETE CASCADE NOT NULL,

  CONSTRAINT PK_BAG_ID PRIMARY KEY (BAG_ID)
);